# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geoproceso
                                 A QGIS plugin
 Geoprocesos de datos vectoriales
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-26
        copyright            : (C) 2024 by Lesby Munguia
        email                : lesby.munguia@unah.hn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Geoproceso class from file Geoproceso.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geoproceso import Geoproceso
    return Geoproceso(iface)
